### ISSUE TITLE
新版能集成吗，我改了空安全，SDK换成4.0.65，启动报错

### ISSUE THREAD

**Issue by wraptor** [TalkingData/AppAnalytics_SDK_Flutter#9]
```
E/AndroidRuntime( 1164): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tendcloud/tenddata/TCAgent;
E/AndroidRuntime( 1164): 	at com.talkingdata.plugin.appanalytics.TalkingDataAppAnalyticsPlugin.onMethodCall(TalkingDataAppAnalyticsPlugin.java:40)
E/AndroidRuntime( 1164): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime( 1164): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/AndroidRuntime( 1164): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:822)
E/AndroidRuntime( 1164): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime( 1164): 	at android.os.MessageQueue.next(MessageQueue.java:335)
```

**Comment by Li-sa-Li** [comment]
请问，你那边初始化，是怎么调用的？
看错误信息定位,是在执行初始化的时候，报的错误；init需要三个参数：Context，appID, channelId;请确认一下参数是否对。

**Comment by wraptor** [comment]
什么content，不是调`https://github.com/TalkingData/AppAnalytics_SDK_Flutter/blob/master/AppAnalytics_SDK_Flutter/lib/talkingdata_appanalytics_plugin.dart`
这个方法吗
```
class TalkingDataAppAnalytics {
  static const MethodChannel _channel =
      const MethodChannel('TalkingData_AppAnalytics');

  static Future<void> init({String appID, String channelID}) async{
    return await _channel.invokeMethod('init', <String, dynamic>{
      'appID': appID,
      'channelID': channelID
    });
  }
}
```

**Comment by Li-sa-Li** [comment]
对的，就是调用Future<void> init({String appID, String channelID})这个接口，出错的。你那边仅仅是更新了SDK吗？代码有变动吗？

**Comment by wraptor** [comment]
引AppAnalytics_SDK_Flutter，代码只改成空安全（加了require和？
其他没有变动
